import type { Metadata } from "next";
import Link from "next/link";
import { AFFILIATE_TIERS, SITE } from "@/lib/catalog";

export const metadata: Metadata = { title: "Affiliate Program" };

const STEPS = [
  {
    emoji: "📝",
    title: "Register",
    desc: "Sign up for a free BSL Gaming affiliate account in minutes. No upfront cost.",
  },
  {
    emoji: "📣",
    title: "Refer Players",
    desc: "Share your unique affiliate link with your network, website, or social media.",
  },
  {
    emoji: "💰",
    title: "Earn Commission",
    desc: "Get lifetime commission up to 45% on every referred player's net revenue.",
  },
];

const BENEFITS = [
  { emoji: "♾️", title: "Lifetime Commission", desc: "Earn forever from every player you refer." },
  { emoji: "📊", title: "Real-Time Stats", desc: "Track clicks, signups, and earnings live." },
  { emoji: "🧑‍💼", title: "Dedicated Manager", desc: "Personal affiliate manager to help you grow." },
  { emoji: "⚡", title: "Fast Payouts", desc: "Withdraw commissions quickly via bKash or Nagad." },
  { emoji: "🎨", title: "Marketing Materials", desc: "Banners, landing pages, and creatives provided." },
  { emoji: "🤝", title: "Custom Deals", desc: "Negotiate custom commission rates for high volume." },
];

const FAQS = [
  {
    q: "How much can I earn as an affiliate?",
    a: "Affiliates earn up to 45% lifetime commission on the net revenue generated by their referred players. Top affiliates earn over ৳5,00,000 per month in commission plus monthly bonuses.",
  },
  {
    q: "When and how do I get paid?",
    a: "Commission payouts are processed monthly. You can withdraw your earnings via bKash, Nagad, Rocket, or bank transfer. Minimum payout threshold is ৳2,000.",
  },
  {
    q: "Is there a cost to join the affiliate program?",
    a: "No. Joining the BSL Gaming affiliate program is completely free. There are no upfront fees or hidden charges. You simply sign up and start referring players.",
  },
  {
    q: "How do I track my referrals and earnings?",
    a: "Once registered, you get access to a real-time affiliate dashboard showing clicks, registrations, active players, net revenue, and your commission earnings updated live.",
  },
];

export default function AffiliatePage() {
  return (
    <div className="space-y-6 px-3 py-4 sm:px-5 sm:py-6">
      <section className="relative overflow-hidden rounded-2xl border border-[#008d5b]/30 bg-gradient-to-br from-[#008d5b] via-[#006640] to-[#0d1f17] p-8 text-center sm:p-12">
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            background:
              "radial-gradient(circle at 50% 0%, rgba(255,223,25,0.12), transparent 60%)",
          }}
        />
        <div className="relative space-y-4">
          <span className="inline-block rounded-full bg-[#ffdf19]/15 px-4 py-1 text-xs font-bold uppercase tracking-wider text-[#ffdf19]">
            BSL Gaming Affiliate Program
          </span>
          <h1 className="text-3xl font-extrabold text-white sm:text-5xl">
            Affiliate Program
          </h1>
          <p className="text-lg font-semibold text-white/90 sm:text-xl">
            Earn lifetime commission up to 45%
          </p>
          <p className="mx-auto max-w-xl text-sm text-white/70">
            Join {SITE.name}'s affiliate program and turn your traffic into
            recurring income. Refer players, earn commission on their net
            revenue for life.
          </p>
          <Link
            href="/register"
            className="btn-primary inline-block rounded-lg px-8 py-3 text-base font-bold text-white"
          >
            Join Now
          </Link>
        </div>
      </section>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <span className="section-title-bar" />
          <span className="text-lg">⚙️</span>
          <h2 className="text-sm font-bold uppercase tracking-wide text-[#f0f0f0] sm:text-base">
            How It Works
          </h2>
        </div>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
          {STEPS.map((step, i) => (
            <div
              key={step.title}
              className="relative rounded-xl border border-[#2a2c30] bg-[#1b1c1e] p-5 text-center"
            >
              <span className="absolute right-3 top-2 text-5xl font-extrabold text-[#2a2c30]">
                {i + 1}
              </span>
              <div className="relative space-y-2">
                <span className="text-4xl">{step.emoji}</span>
                <h3 className="text-base font-bold text-[#f0f0f0]">
                  {step.title}
                </h3>
                <p className="text-xs text-[#9ca3af]">{step.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <span className="section-title-bar" />
          <span className="text-lg">💎</span>
          <h2 className="text-sm font-bold uppercase tracking-wide text-[#f0f0f0] sm:text-base">
            Commission Tiers
          </h2>
        </div>
        <div className="overflow-hidden rounded-xl border border-[#2a2c30] bg-[#1b1c1e]">
          <table className="w-full text-left text-xs sm:text-sm">
            <thead>
              <tr className="border-b border-[#2a2c30] bg-[#242628] text-[10px] uppercase tracking-wider text-[#6b7280]">
                <th className="px-4 py-3 font-semibold">Tier</th>
                <th className="px-4 py-3 font-semibold">Commission %</th>
                <th className="px-4 py-3 font-semibold">Active Players Required</th>
                <th className="px-4 py-3 text-right font-semibold">Monthly Bonus</th>
              </tr>
            </thead>
            <tbody>
              {AFFILIATE_TIERS.map((t) => (
                <tr
                  key={t.tier}
                  className={`border-b border-[#2a2c30]/60 ${
                    t.tier === "Diamond"
                      ? "bg-[#ffdf19]/5"
                      : "bg-[#1b1c1e]"
                  }`}
                >
                  <td className="px-4 py-3">
                    <span
                      className={`font-bold ${
                        t.tier === "Diamond"
                          ? "text-[#ffdf19]"
                          : t.tier === "Platinum"
                          ? "text-[#22c55e]"
                          : "text-[#f0f0f0]"
                      }`}
                    >
                      {t.tier}
                    </span>
                  </td>
                  <td className="px-4 py-3 font-mono font-bold text-[#22c55e]">
                    {t.commission}
                  </td>
                  <td className="px-4 py-3 text-[#9ca3af]">
                    {t.requirement}
                  </td>
                  <td className="px-4 py-3 text-right font-bold text-[#ffdf19]">
                    {t.monthlyBonus}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <span className="section-title-bar" />
          <span className="text-lg">✨</span>
          <h2 className="text-sm font-bold uppercase tracking-wide text-[#f0f0f0] sm:text-base">
            Benefits
          </h2>
        </div>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {BENEFITS.map((b) => (
            <div
              key={b.title}
              className="rounded-xl border border-[#2a2c30] bg-[#1b1c1e] p-4 transition hover:border-[#383b3f]"
            >
              <div className="flex items-start gap-3">
                <span className="text-3xl">{b.emoji}</span>
                <div className="space-y-1">
                  <h3 className="text-sm font-bold text-[#f0f0f0]">
                    {b.title}
                  </h3>
                  <p className="text-xs text-[#9ca3af]">{b.desc}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <span className="section-title-bar" />
          <span className="text-lg">❓</span>
          <h2 className="text-sm font-bold uppercase tracking-wide text-[#f0f0f0] sm:text-base">
            Frequently Asked Questions
          </h2>
        </div>
        <div className="space-y-2">
          {FAQS.map((faq) => (
            <div
              key={faq.q}
              className="rounded-xl border border-[#2a2c30] bg-[#1b1c1e] p-4"
            >
              <h3 className="text-sm font-bold text-[#f0f0f0]">{faq.q}</h3>
              <p className="mt-1.5 text-xs leading-relaxed text-[#9ca3af]">
                {faq.a}
              </p>
            </div>
          ))}
        </div>
      </section>

      <section className="relative overflow-hidden rounded-2xl border border-[#ffdf19]/30 bg-gradient-to-br from-[#2e1065] via-[#1e1b4b] to-[#0c4a6e] p-8 text-center">
        <div className="relative space-y-4">
          <h2 className="text-2xl font-extrabold text-white sm:text-3xl">
            Start Earning Today
          </h2>
          <p className="mx-auto max-w-md text-sm text-white/80">
            Join thousands of affiliates already earning lifetime commission
            with {SITE.name}.
          </p>
          <Link
            href="/register"
            className="btn-primary inline-block rounded-lg bg-[#008d5b] px-8 py-3 text-base font-bold text-white"
          >
            Become an Affiliate
          </Link>
        </div>
      </section>
    </div>
  );
}
